#ifndef CYGONCE_PKGCONF_HAL_CORTEXM_VYBRID_H
#define CYGONCE_PKGCONF_HAL_CORTEXM_VYBRID_H
/*
 * File <pkgconf/hal_cortexm_vybrid.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_HAL_CORTEXM_PRIORITY_LEVEL_BITS 4
#define CYGNUM_HAL_CORTEXM_PRIORITY_LEVEL_BITS_4
#define CYGNUM_HAL_KERNEL_COUNTERS_CLOCK_ISR_DEFAULT_PRIORITY 0x000000E0
#define CYGNUM_HAL_KERNEL_COUNTERS_CLOCK_ISR_DEFAULT_PRIORITY_0x000000E0
#define CYGNUM_HAL_RTC_NUMERATOR 1000000000
#define CYGNUM_HAL_RTC_NUMERATOR_1000000000
#define CYGNUM_HAL_RTC_DENOMINATOR 1000
#define CYGNUM_HAL_RTC_DENOMINATOR_1000
#define CYGNUM_HAL_RTC_PERIOD 1000
#define CYGNUM_HAL_RTC_PERIOD_1000
#define CYG_HAL_STARTUP DRAM
#define CYG_HAL_STARTUP_DRAM
#define CYGHWR_HAL_CORTEXM_VYBRID_OCRAM_KIB 256
#define CYGHWR_HAL_CORTEXM_VYBRID_OCRAM_KIB_256
#define CYGHWR_HAL_CORTEXM_VYBRID_OCRAM 0x00040000
#define CYGHWR_HAL_CORTEXM_VYBRID_OCRAM_0x00040000
#define CYGHWR_HAL_CORTEXM_VYBRID_TCMU_KIB 32
#define CYGHWR_HAL_CORTEXM_VYBRID_TCMU_KIB_32
#define CYGHWR_HAL_CORTEXM_VYBRID_TCMU 0x00008000
#define CYGHWR_HAL_CORTEXM_VYBRID_TCMU_0x00008000
#define CYGHWR_HAL_CORTEXM_VYBRID_TCML_KIB 32
#define CYGHWR_HAL_CORTEXM_VYBRID_TCML_KIB_32
#define CYGHWR_HAL_CORTEXM_VYBRID_TCML 0x00008000
#define CYGHWR_HAL_CORTEXM_VYBRID_TCML_0x00008000
#define CYGINT_HAL_CACHE 1
#define CYGINT_HAL_CORTEXM_VYBRID_DDRAM 1
#define CYGINT_HAL_FREESCALE_UART1 1
#define CYGINT_HAL_FREESCALE_UART2 1

#endif
