#ifndef CYGONCE_PKGCONF_HAL_CORTEXM_VYBRID_COL_VF61_H
#define CYGONCE_PKGCONF_HAL_CORTEXM_VYBRID_COL_VF61_H
/*
 * File <pkgconf/hal_cortexm_vybrid_col_vf61.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define HAL_PLATFORM_CPU    "Cortex-M4"
#define HAL_PLATFORM_BOARD  "Toradex Colibri VF61"
#define HAL_PLATFORM_EXTRA  ""
#define CYGHWR_HAL_CORTEXM_VYBRID_DRAM_KIB 16384
#define CYGHWR_HAL_CORTEXM_VYBRID_DRAM_KIB_16384
#define CYGHWR_HAL_CORTEXM_VYBRID_DRAM 0x01000000
#define CYGHWR_HAL_CORTEXM_VYBRID_DRAM_0x01000000
#define CYG_HAL_VTOR_ADRESS 0x0F000000
#define CYG_HAL_VTOR_ADRESS_0x0F000000
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS 2
#define CYGNUM_HAL_VIRTUAL_VECTOR_COMM_CHANNELS_2
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL 1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_1
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_CONSOLE_CHANNEL_BAUD_115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD 115200
#define CYGNUM_HAL_VIRTUAL_VECTOR_DEBUG_CHANNEL_BAUD_115200
#define CYGHWR_HAL_DEVS_IRQ_PRIO_SCHEME 1
#define CYGBLD_GLOBAL_OPTIONS 1

#endif
