#ifndef CYGONCE_PKGCONF_IO_SERIAL_FREESCALE_UART_H
#define CYGONCE_PKGCONF_IO_SERIAL_FREESCALE_UART_H
/*
 * File <pkgconf/io_serial_freescale_uart.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGINT_IO_SERIAL_FREESCALE_UART0 1
#define CYGINT_IO_SERIAL_FREESCALE_UART1 1
#define CYGPKG_IO_SERIAL_FREESCALE_UART1 1
#define CYGDAT_IO_SERIAL_FREESCALE_UART1_NAME "/dev/ser1"
#define CYGNUM_IO_SERIAL_FREESCALE_UART1_BAUD 115200
#define CYGNUM_IO_SERIAL_FREESCALE_UART1_BAUD_115200
#define CYGNUM_IO_SERIAL_FREESCALE_UART1_BUFSIZE 128
#define CYGNUM_IO_SERIAL_FREESCALE_UART1_BUFSIZE_128
#define CYGNUM_IO_SERIAL_FREESCALE_UART1_INT_PRIORITY 0x00000080
#define CYGNUM_IO_SERIAL_FREESCALE_UART1_INT_PRIORITY_0x00000080
#define CYGINT_IO_SERIAL_FREESCALE_UART2 1
#define CYGPKG_IO_SERIAL_FREESCALE_UART2 1
#define CYGDAT_IO_SERIAL_FREESCALE_UART2_NAME "/dev/ser2"
#define CYGNUM_IO_SERIAL_FREESCALE_UART2_BAUD 115200
#define CYGNUM_IO_SERIAL_FREESCALE_UART2_BAUD_115200
#define CYGNUM_IO_SERIAL_FREESCALE_UART2_BUFSIZE 128
#define CYGNUM_IO_SERIAL_FREESCALE_UART2_BUFSIZE_128
#define CYGNUM_IO_SERIAL_FREESCALE_UART2_INT_PRIORITY 0x00000080
#define CYGNUM_IO_SERIAL_FREESCALE_UART2_INT_PRIORITY_0x00000080
#define CYGINT_IO_SERIAL_FREESCALE_UART3 1
#define CYGINT_IO_SERIAL_FREESCALE_UART4 1
#define CYGINT_IO_SERIAL_FREESCALE_UART5 1
#define CYGDAT_IO_SERIAL_TTY_ADD_INL <cyg/io/ser_freescale_uart_tty_add.inl>
#define CYGPKG_IO_SERIAL_FREESCALE_UART_OPTIONS 1

#endif
